// @flow

export const CHANGE_AMOUNT_START = 'CHANGE_AMOUNT_START'
export const CHANGE_AMOUNT_SUCCESS = 'CHANGE_AMOUNT_SUCCESS'
export const CLEAR_AMOUNT = 'CLEAR_AMOUNT'
export const AMOUNT_IS_THE_SAME = 'AMOUNT_IS_THE_SAME'

export const CHANGE_CURRENCY_START = 'CHANGE_CURRENCY_START'
export const CHANGE_CURRENCY_SUCCESS = 'CHANGE_CURRENCY_SUCCESS'

export const GET_EXCHANGE_RATE_START = 'GET_EXCHANGE_RATE_START'
export const GET_EXCHANGE_RATE_SUCCESS = 'GET_EXCHANGE_RATE_SUCCESS'
export const GET_EXCHANGE_RATE_FAIL = 'GET_EXCHANGE_RATE_FAIL'
export const REFETCH_EXCHANGE_RATE = 'REFETCH_EXCHANGE_RATE'

export const COUNT_PRICE_RATIO = 'COUNT_PRICE_RATIO'

export const TRANSFER_PAYMENT_START = 'TRANSFER_PAYMENT_START'
export const TRANSFER_PAYMENT_SUCCESS = 'TRANSFER_PAYMENT_SUCCESS'
export const TRANSFER_PAYMENT_FAIL = 'TRANSFER_PAYMENT_FAIL'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'
