export const CHANGE_AMOUNT_START = 'CHANGE_AMOUNT_START'
export const CHANGE_AMOUNT_SUCCESS = 'CHANGE_AMOUNT_SUCCESS'

export const CHANGE_CURRENCY_START = 'CHANGE_CURRENCY_START'
export const CHANGE_CURRENCY_SUCCESS = 'CHANGE_CURRENCY_SUCCESS'
